stages:
- build

build-helmfile-image:
  stage: build
  image:
    name: registry.cern.ch/gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
  # Set GitLab Registry Login Info
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  # Set GitLab Registry CA
  - echo "$CA_CERTIFICATE" | base64 -d >> /kaniko/ssl/certs/ca-certificates.crt
  script:
  # Docker Build && Push image
  - cat Dockerfile
  - /kaniko/executor --cache=true --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

